name: Set up WireGuard
description: Set up WireGuard connection

inputs:
  endpoint:
    description: Endpoint in the HOST:PORT format
    required: true
  endpoint_public_key:
    description: Public key of the endpoint
    required: true
  ips:
    description: Comma-separated list of IP addresses
    required: true
  allowed_ips:
    description: Comma-separated list of netmasks
    required: true
  private_key:
    description: Private key
    required: true
  preshared_key:
    description: Preshared key
    required: false
  keepalive:
    description: Useful for NAT traversal
    required: false

runs:
  using: composite
  steps:
    - run: ${GITHUB_ACTION_PATH}/wg-setup.sh
      shell: bash
      env:
        ARG_ENDPOINT: ${{ inputs.endpoint }}
        ARG_ENDPOINT_PUBLIC_KEY: ${{ inputs.endpoint_public_key }}
        ARG_ASSIGNED_IPS: ${{ inputs.ips }}
        ARG_ALLOWED_IPS: ${{ inputs.allowed_ips }}
        ARG_PRIVATE_KEY: ${{ inputs.private_key }}
        ARG_PRESHARED_KEY: ${{ inputs.preshared_key }}
        ARG_KEEPALIVE: ${{ inputs.keepalive }}

branding:
  icon: star
  color: green
